openapi: 3.0.3
info:
  title: DeenMate API
  version: 1.0.0
  description: Islamic content API for DeenMate mobile application
servers:
  - url: https://api.deenmate.app/v1
    description: Production server
  - url: https://staging-api.deenmate.app/v1
    description: Staging server
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
